### ISSUE TITLE
Sync Gateway does not start with docker-compose

### ISSUE THREAD

**Issue by PlutoHDDev** [couchbase/docker#187]
I have created this `docker-compose.yml` file:

```yml
version: '3.5'
            
networks:
    couchbase:

services:
    server:
        container_name: couchbase-server
        ports:
            - '8091-8096:8091-8096'
            - '11207-11211:11207-11211'
            - '18091-18093:18091-18093'
        networks:
            - couchbase
        image: couchbase
        volumes:
            - /root/docker/couchbase/server/data:/opt/couchbase/var
        ulimits:
            nofile:
                soft: 200000
                hard: 200000
            core:
                soft: 100000000
                hard: 100000000
            memlock:
                soft: 100000000
                hard: 100000000
    sync-gateway:
        networks:
            - couchbase
        ports:
            - '4984:4984'
        container_name: couchbase-sync-gateway
        volumes:
            - /root/docker/couchbase/sync-gateway/config:/tmp/config
            - /root/docker/couchbase/sync-gateway/data:/opt/couchbase-sync-gateway
        image: couchbase/sync-gateway
        command: '/tmp/config/sync-gateway-config.json'
        depends_on:
            - server
```

and this is my `sync-gateway-config.json` file:

```json
{
    "bootstrap": {
        "server": "couchbases://couchbase-server:8091",
        "server_tls_skip_verify": true,
        "username": "...",
        "password": "..."
    },
    "logging": {
        "console": {
            "enabled": true,
            "log_level": "info",
            "log_keys": [
                "*"
            ]
        }
    }
}
```

When I run `docker-compose up -d`, the Server starts without any issues and I can set it up using the web interface, but the Sync Gateway is stopped with this error message:

`/entrypoint.sh: line 7: exec: sync_gateway: not found`

What could cause this issue and how can I resolve it?
