### ISSUE TITLE
How to use image for CI?

### ISSUE THREAD

**Issue by StarpTech** [couchbase/docker#73]
Hi, I'm planning to use couchbase but I couldn't find a solution to automate the installation of the database. I want to run it on travis or appveyor. What's the way to go here?

**Comment by ceejatec** [comment]
Do you mean configuration of the database, ie, setting up buckets, configuring memory limits, etc?

**Comment by StarpTech** [comment]
Hi @ceejatec I'm talking about a simple way to start the server without any manual intervention. I want run tests with the couchnode driver on travis or any other ci environment.

**Comment by StarpTech** [comment]
I could find a sample travis script but I don't know if its work. It's the rigt way?

https://github.com/evantahler/couchbase-structures/blob/master/.travis.yml

**Comment by ceejatec** [comment]
I know nothing about Travis, but from that file it appears that it's installing Couchbase from a package. Since you posted this question on the couchbase/docker repository, I assumed you were trying to do some automation involving the Couchbase Docker image - is that not correct?

**Comment by StarpTech** [comment]
No no when it's possible with docker it would be great. I'm looking for a solution to cover this with docker.

**Comment by ceejatec** [comment]
There's an official Docker image for Couchbase Server; "docker run couchbase". More information about that can be found on Docker Hub: https://hub.docker.com/_/couchbase/

That should eliminate the need to install Couchbase Server. That takes me back to my initial question, though: are you looking to automate the configuration of the Server? (If you just run the "couchbase" image, you'll get a default server instance, and if you hit the web interface you'll be presented with the Setup Wizard.)

**Comment by StarpTech** [comment]
Yes, I'm looking for a way to automate the configuration of the Server. On a CI platform there is no UI.

**Comment by ceejatec** [comment]
Well, I won't claim it's necessarily the best way, but take a look at https://github.com/couchbaselabs/analytics-docker/blob/master/scripts/configure-node.sh .

If you create a custom Docker image with a Dockerfile something like

FROM couchbase
COPY scripts/configure-node.sh /etc/service/config-couchbase/run

Then it'll run the commands in that script after Couchbase initially comes up. That's good enough for configuring things like memory limits, which services are enabled, etc. (It might be easier to do the configuration with couchbase-cli rather than direct REST calls.)

Note: the block at the bottom of that script that starts "if [ "$TYPE" = "WORKER" ]" doesn't actually work. It's intended for use when running the image in multiple containers to allow them to automatically join together into a cluster. It would probably work except that the runit process manager in the container strips out environment variables from "docker run -e". I haven't gotten around to fixing that yet.

**Comment by StarpTech** [comment]
What do you mean with 

> Well, I won't claim it's necessarily the best way, but take a look at 

what's the alternative to setup couchbase in headless mode?

**Comment by StarpTech** [comment]
so there is no official examples or documentation about how to setup couchbase with docker or on localhost without to thtough the setup ? How do you do CI tests?

**Comment by ceejatec** [comment]
Our testing (to the best of my knowledge - I'm not in QA) treats Docker testing the same as normal platform testing, and does cluster configuration from outside the cluster itself using couchbase-cli in the way we expect customer deployments work. Our documentation certainly covers this use case, eg. https://developer.couchbase.com/documentation/server/4.6/cli/cli-intro.html .

My suggestion was for a way to get the Docker image itself to configure the node from inside, so it's self-contained. That may or may not meet your needs.

**Comment by StarpTech** [comment]
Thanks for the insides. Is it possible to skip the `Setup Wizard` with the couchbase-cli in the container?

**Comment by ceejatec** [comment]
Yes; a node configured using the script I showed will no longer show the Setup Wizard when you visit the web interface. I'm not positive which step sets the node into the "configured" state such that the Wizard is no longer necessary, but I believe it's either the "Configure Services" or "Set up credentials" step (or possibly both together) which do so.

**Comment by StarpTech** [comment]
All right and thanks. I will try it.

**Comment by StarpTech** [comment]
Hi @ceejatec how can I access  the `couchbase-cli` tool ?

```
version: "3"
services:
  db:
    image: couchbase
    command: 
      - /opt/couchbase/bin/tools/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-init-username=Administrator --cluster-init-password=password --cluster-init-ramsize=256
      - /opt/couchbase/bin/tools/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=default --bucket-password=password --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=100 --bucket-replica=0 -u Administrator -p password
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
      - 11211:11211
```

error
```
db_1  | /entrypoint.sh: line 9: /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-init-username=Administrator --cluster-init-password=password --cluster-init-ramsize=256: No such file or directory
```
